/**
 * GENERATED by scripts/build-nutrition.mjs — do not edit.
 *
 * Companion constants for ./ingredients.json, so the first-run import can decide whether
 * it needs the file before fetching it.
 */

/** Bumped whenever the bundled data changes; IndexedDB stores the value it imported. */
export const NUTRITION_DATA_VERSION = 2;

/** How many ingredients the bundle holds. */
export const NUTRITION_INGREDIENT_COUNT = 1344;

/** The pinned USDA FoodData Central releases the bundle was built from. */
export const NUTRITION_SOURCES = ["sr_legacy_2018-04","foundation_2026-04-30"] as const;

/** Polish attribution shown on the credits screen. FDC is CC0; attribution is requested. */
export const NUTRITION_ATTRIBUTION =
  "Dane o wartościach odżywczych: U.S. Department of Agriculture, Agricultural Research Service, FoodData Central (fdc.nal.usda.gov). Domena publiczna (CC0).";
